# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LabelWatch < Formula
  desc "label-watch checks a specific label on worker node then create an label"
  homepage "https://github.com/kolikons/label-watch"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kolikons/label-watch/releases/download/v0.0.1/label-watch_0.0.1_darwin_amd64.tar.gz"
      sha256 "67245838895ff07aac9ad16d26a30978075ec079de1288952b1d87f5c04d2040"

      def install
        bin.install "label-watch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kolikons/label-watch/releases/download/v0.0.1/label-watch_0.0.1_darwin_arm64.tar.gz"
      sha256 "84414e13b2305e7d5585333e3cc95bc4c369536fb1d43e6f99ae18f892a03297"

      def install
        bin.install "label-watch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kolikons/label-watch/releases/download/v0.0.1/label-watch_0.0.1_linux_amd64.tar.gz"
      sha256 "771803be26c7ea2283b35aa1021e64578d3582bb0dbca4c74d49cda8b95abb43"

      def install
        bin.install "label-watch"
      end
    end
  end

  test do
    system "#{bin}/label-watch --help"
  end
end
