# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LabelWatch < Formula
  desc "label-watch checks a specific label on worker node then create an label"
  homepage "https://github.com/kolikons/label-watch"
  version "0.0.2-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kolikons/label-watch/releases/download/v0.0.2-rc1/label-watch_0.0.2-rc1_darwin_amd64.tar.gz"
      sha256 "05598a1b44f8c9c9e31426350a9920ea9bd91786b4328e83664617db25a9e6d2"

      def install
        bin.install "label-watch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kolikons/label-watch/releases/download/v0.0.2-rc1/label-watch_0.0.2-rc1_darwin_arm64.tar.gz"
      sha256 "5afc915f15ccc7ad1bcb0fca25c06f3bc799d13b2ae21c39ae42d732360008ac"

      def install
        bin.install "label-watch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kolikons/label-watch/releases/download/v0.0.2-rc1/label-watch_0.0.2-rc1_linux_amd64.tar.gz"
      sha256 "e3daca21e006c5b75ec2587e01bc9185167550aab4ddfebfb4e92dfacfd1a0bc"

      def install
        bin.install "label-watch"
      end
    end
  end

  test do
    system "#{bin}/label-watch --help"
  end
end
