# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LabelWatch < Formula
  desc "label-watch checks a specific label on worker node then create an label"
  homepage "https://github.com/kolikons/label-watch"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kolikons/label-watch/releases/download/v0.0.2/label-watch_0.0.2_darwin_amd64.tar.gz"
      sha256 "5b72759132ef44767e5562c2f5eee1f3a79cffeda8ea0be4fb345eb737ef8875"

      def install
        bin.install "label-watch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kolikons/label-watch/releases/download/v0.0.2/label-watch_0.0.2_darwin_arm64.tar.gz"
      sha256 "2acaa458dbfca527dfd4c46c2445fb08564a2efd3267c98ae528a61ebbcfa978"

      def install
        bin.install "label-watch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kolikons/label-watch/releases/download/v0.0.2/label-watch_0.0.2_linux_amd64.tar.gz"
      sha256 "dd639de7183c751939d3f689169560bc23884448f39e44ab008c9dd70656fffa"

      def install
        bin.install "label-watch"
      end
    end
  end

  test do
    system "#{bin}/label-watch --help"
  end
end
